import { getSiteUrl } from "@/lib/site-url"

// Posts a published blog post to the configured Facebook Page feed.
// No-ops safely if env is unset or the API call fails — publishing must never
// break because Facebook is down. The link preview (cover image, title,
// description) is generated by Facebook from the blog post's Open Graph tags.

const PAGE_ID = process.env.FACEBOOK_PAGE_ID
const TOKEN = process.env.FACEBOOK_PAGE_ACCESS_TOKEN
const GRAPH_VERSION = process.env.FACEBOOK_GRAPH_VERSION || "v21.0"

type FacebookBlogPost = {
  slug: string
  title: string
  summary: string
}

export async function postBlogToFacebook(post: FacebookBlogPost): Promise<void> {
  if (!PAGE_ID || !TOKEN) return // feature disabled — skip silently

  const url = `${getSiteUrl()}/blog/${post.slug}`
  const message = `${post.title}\n\n${post.summary.trim()}\n\nRead the full article 👇`

  try {
    const body = new URLSearchParams({
      message,
      link: url, // Facebook builds the preview card from the page's OG tags
      access_token: TOKEN,
    })
    const res = await fetch(`https://graph.facebook.com/${GRAPH_VERSION}/${PAGE_ID}/feed`, {
      method: "POST",
      body,
    })
    const detail = await res.text().catch(() => "")
    if (!res.ok) {
      // Full Graph API error body — includes error.code / error.message so you
      // can tell an App-mode/permission block from a bad token or unpublished page.
      console.error(`[facebook] post FAILED (${res.status}) for /blog/${post.slug}:`, detail)
      return
    }
    // Success — response is { "id": "<pageId>_<postId>" }. Log it so a publish
    // can be confirmed from server logs and opened at facebook.com/<id>.
    let postId = ""
    try {
      postId = (JSON.parse(detail) as { id?: string }).id ?? ""
    } catch {
      /* non-JSON success body — fall through with empty id */
    }
    console.log(`[facebook] post published: id=${postId || "(unknown)"} for /blog/${post.slug} — ${detail}`)
  } catch (err) {
    console.error("Facebook post threw:", err)
  }
}
