import { getSiteUrl } from "@/lib/site-url"

// Posts a published blog post to the configured Facebook Page feed.
// No-ops safely if env is unset or the API call fails — publishing must never
// break because Facebook is down. The link preview (cover image, title,
// description) is generated by Facebook from the blog post's Open Graph tags.

const PAGE_ID = process.env.FACEBOOK_PAGE_ID
const TOKEN = process.env.FACEBOOK_PAGE_ACCESS_TOKEN
const GRAPH_VERSION = process.env.FACEBOOK_GRAPH_VERSION || "v21.0"

type FacebookBlogPost = {
  slug: string
  title: string
  summary: string
}

export async function postBlogToFacebook(post: FacebookBlogPost): Promise<void> {
  if (!PAGE_ID || !TOKEN) return // feature disabled — skip silently

  const url = `${getSiteUrl()}/blog/${post.slug}`
  const message = `${post.title}\n\n${post.summary.trim()}\n\nRead the full article 👇`

  try {
    const body = new URLSearchParams({
      message,
      link: url, // Facebook builds the preview card from the page's OG tags
      access_token: TOKEN,
    })
    const res = await fetch(`https://graph.facebook.com/${GRAPH_VERSION}/${PAGE_ID}/feed`, {
      method: "POST",
      body,
    })
    if (!res.ok) {
      const detail = await res.text().catch(() => "")
      console.error(`Facebook post failed (${res.status}):`, detail)
    }
  } catch (err) {
    console.error("Facebook post threw:", err)
  }
}
